#!/bin/bash
# Script to display system info when logging into a shell window
# 1.) Make this script executable 
# 2.) Call it at the bottom of your ~/.basrhc script to install/run whenever "bash" is executed with your uid.
# Very handy for SSH connections


VERSION="2.0"

PROCCOUNT=`ps -l | wc -l`
PROCCOUNT=`expr $PROCCOUNT - 4`

if [[ $(groups) == *irc* ]]; then
ENDPROC=`cat /etc/security/limits.conf | grep "@irc" | grep nproc | awk {'print $4'}`
ENDSESSION=`cat /etc/security/limits.conf | grep "@irc" | grep maxlogins | awk {'print $4'}`
PRIVLAGED="IRC Account"
else
ENDPROC=`cat /etc/security/limits.conf | grep "*" | grep nproc | awk {'print $4'}`
ENDSESSION="Unlimited"
PRIVLAGED="Regular User"
fi

echo -e "
+++++++++++++++++: System Data :+++++++++++++++++++
+ Hostname = `hostname`
+ Uptime = `uptime | sed 's/.*up ([^,]*), .*/1/'`
+ IP Addresses: `ifconfig | grep -v 127.0.0.1 | grep -i "inet\ " | awk -F: '{ print $1 }' | awk '{ print $2 }'`
+ Memory (MB): `echo "" && free -m | grep -v +`
++++++++++++++++++: User Data :++++++++++++++++++++
+ Username = `whoami`
+ Privlages = $PRIVLAGED
+ Sessions = `who | grep $USER | wc -l` of $ENDSESSION MAX
+ Processes = $PROCCOUNT of $ENDPROC MAX"

if [ ! "`which VBoxManage`" ]; then
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
else echo -e "
+++++++++: Running VirtualBox Machines :+++++++++++
`VBoxManage list runningvms`
+++++++++++++++++++++++++++++++++++++++++++++++++++
"
fi

exit 0

