#!/bin/bash
# Easy-button script to block and unblock IPs with iptables

VERSION="1.0"

if [ ! $2 ]; then
echo "Usage: $0 {block | unblock} {IP ADDRESS}"
exit 1
fi

if [ "$UID" != "0" ];then
echo "I am not root, lets try again with sudo..."
sudo $0 $1 $2
exit 1
fi

TARGET=$2

function block_ips() {
	echo "Blocking: $TARGET"
	if [ ! "`iptables -L -n -w | grep $TARGET`" ];then
	iptables -A INPUT -w -s $TARGET -j DROP
        iptables -A OUTPUT -w -d $TARGET -j DROP
	else echo "Already blocking that guy."
	fi
}

function unblock_ips() {
	echo "UN-Blocking: $TARGET"
	if [ "`iptables -L -n -w | grep $TARGET`" ];then
	iptables -D INPUT -w -s $TARGET -j DROP
	iptables -D OUTPUT -w -d $TARGET -j DROP
	fi
}

function list_tables() {
	echo -n 'Would you like to view the new tables? [y/N] '
	read answer
	case $answer in
		y|Y )
			iptables -L -w --numeric | grep $TARGET
			;;
		*)
			echo "Skipping table list...."
			;;
	esac
}

case "$1" in

	("block")
		block_ips
		list_tables
	;;

	("unblock")
		unblock_ips
		list_tables
	;;

	*)
		echo "Usage: $0 { block | unblock } {IP ADDRESS}"
        ;;
esac

exit 0
