#!/bin/bash

# version 3.0

WORKINGDIR="OS-Settings-Backup" 

if [ $1 == "restore" ]; then
if [ $2 ]; then
sudo apt-key add $2/Repo.keys
sudo cp -R $2/sources/sources.list* /etc/apt/
sudo apt-get update
sudo apt-get install dselect
sudo dselect update
sudo dpkg --set-selections < $2/Package.list
sudo apt-get dselect-upgrade -y
exit 0
else 
echo "Usage: $0 restore /backup/directory"
exit 1
fi
else
echo -e "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Usage: 
To Backup Just run $0

To restore packages from a previous backup: 
$0 restore /backup/directory
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
fi

echo "Setting up working directory, please wait..."
mkdir $WORKINGDIR
mkdir $WORKINGDIR/sources

echo "Backing up current package selections..."
dpkg --get-selections | grep -v deinstall > $WORKINGDIR/installed-packages
dpkg --get-selections > $WORKINGDIR/Package.list
sudo cp -R /etc/apt/sources.list* $WORKINGDIR/sources/
sudo apt-key exportall > $WORKINGDIR/Repo.keys

echo "Backing up the /etc Folder..."
sudo cp -a /etc $WORKINGDIR/

echo "Moving and resetting working directory..."
mv $WORKINGDIR $WORKINGDIR--`date +%m.%d.%y.%H.%M.%S`

echo "Backup Completed."
echo ""
exit 0
